# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CombinationScript_DK.py
# Created on: 2019-10-22 14:07:08.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: CombinationScript_DK <Original_Dataset> <Delta_Parsed123> <Input_Address_Fields> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Original_Dataset = arcpy.GetParameterAsText(0)
if Original_Dataset == '#' or not Original_Dataset:
    Original_Dataset = "ParkOriginal" # provide a default value if unspecified

Delta_Parsed123 = arcpy.GetParameterAsText(1)
if Delta_Parsed123 == '#' or not Delta_Parsed123:
    Delta_Parsed123 = "\\\\10.12.1.112\\TeamWorkspaces\\KirkD\\DeltaTest.gdb\\Delta_Parsed123" # provide a default value if unspecified

Input_Address_Fields = arcpy.GetParameterAsText(2)
if Input_Address_Fields == '#' or not Input_Address_Fields:
    Input_Address_Fields = "FSA" # provide a default value if unspecified

# Local variables:
GarfieldOG = Original_Dataset
GarfieldOG__3_ = GarfieldOG
GarfieldOriginal2__2_ = GarfieldOG__3_
GarfieldOriginal2__3_ = GarfieldOG__3_
GarfieldOriginal2__4_ = GarfieldOG__3_
GarfieldOriginal2__5_ = GarfieldOG__3_
GarfieldOriginal2__7_ = GarfieldOG__3_
GarfieldOriginal2__9_ = GarfieldOG__3_
GarfieldOriginal2__11_ = GarfieldOG__3_
GarfieldOriginal2__12_ = GarfieldOG__3_
BetterAddress_shp = GarfieldOG__3_
BetterAddress_shp__2_ = GarfieldOG__3_
ParkOriginal = GarfieldOG__3_
Delta_Parsed123__12_ = Delta_Parsed123
Delta_Parsed123__5_ = Delta_Parsed123
Delta_Parsed123__9_ = Delta_Parsed123
Delta_Parsed123__6_ = Delta_Parsed123
Delta_Parsed123__11_ = Delta_Parsed123
Delta_Parsed123__2_ = Delta_Parsed123
Delta_Parsed123__8_ = Delta_Parsed123
Delta_Parsed123__7_ = Delta_Parsed123

# Process: Define Projection
arcpy.DefineProjection_management(Original_Dataset, "GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Add XY Coordinates
arcpy.AddXY_management(GarfieldOG)

# Process: Add Field
arcpy.AddField_management(GarfieldOG__3_, "AddrNum", "TEXT", "", "", "10", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (2)
arcpy.AddField_management(GarfieldOG__3_, "NumSuf", "TEXT", "", "", "5", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(GarfieldOG__3_, "PreDir", "TEXT", "", "", "10", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(GarfieldOG__3_, "PreType", "TEXT", "", "", "50", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (6)
arcpy.AddField_management(GarfieldOG__3_, "PostType", "TEXT", "", "", "20", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (8)
arcpy.AddField_management(GarfieldOG__3_, "UnitType", "TEXT", "", "", "20", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (10)
arcpy.AddField_management(GarfieldOG__3_, "AddrFull", "TEXT", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (11)
arcpy.AddField_management(GarfieldOG__3_, "PlaceName", "TEXT", "", "", "50", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Standardize Addresses
arcpy.StandardizeAddresses_geocoding(Original_Dataset, Input_Address_Fields, "US Address - Single House Subaddress", "HouseNum;PreDir;PreType;StreetName;SufType;SufDir;SubAddrType;SubAddrUnit", Delta_Parsed123, "Static")

# Process: Calculate Field
arcpy.CalculateField_management(Delta_Parsed123, "AddrNum", "[SAN]", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Delta_Parsed123, "PreDir", "[PRD]", "VB", "")

# Process: Calculate Field (6)
arcpy.CalculateField_management(Delta_Parsed123, "PostType", "[STS]", "VB", "")

# Process: Add Field (7)
arcpy.AddField_management(GarfieldOG__3_, "PostDir", "TEXT", "", "", "10", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (4)
arcpy.CalculateField_management(Delta_Parsed123, "PlaceName", "[PCN]", "VB", "")

# Process: Add Field (9)
arcpy.AddField_management(GarfieldOG__3_, "UnitNumber", "TEXT", "", "", "50", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (8)
arcpy.CalculateField_management(Delta_Parsed123, "UnitType", "[UTY]", "VB", "")

# Process: Calculate Field (9)
arcpy.CalculateField_management(Delta_Parsed123, "PreType", "[PRETYPE]", "VB", "")

# Process: Calculate Field (10)
arcpy.CalculateField_management(Delta_Parsed123, "PreDir", "[PRD]", "VB", "")

# Process: Calculate Field (11)
arcpy.CalculateField_management(Delta_Parsed123, "NumSuf", "[SNS]", "VB", "")

# Process: Add Field (5)
arcpy.AddField_management(GarfieldOG__3_, "StreetName", "TEXT", "", "", "50", "", "NULLABLE", "NON_REQUIRED", "")

